apiVersion: v1
kind: Namespace
metadata:
  name: aspnet-api-containerized
---
apiVersion: v1
kind: Secret
metadata:
  name: skiservice-secret
  namespace: aspnet-api-containerized
type: Opaque
data:
  # Server=mssql,1433;Database=JetStream;User ID=SA;Password=AStrong!Passw0rd;TrustServerCertificate=True;
  # encoded using echo -n "<connection-string>" | base64
  connection-string: U2VydmVyPW1zc3FsLDE0MzM7RGF0YWJhc2U9SmV0U3RyZWFtO1VzZXIgSUQ9U0E7UGFzc3dvcmQ9QVN0cm9uZ1whUGFzc3cwcmQ7VHJ1c3RTZXJ2ZXJDZXJ0aWZpY2F0ZT1UcnVlOw==
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: skiservice-logs-pv
  namespace: aspnet-api-containerized
  labels:
    type: skiservice-logs
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/skiservice_logs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: skiservice-logs-pvc
  namespace: aspnet-api-containerized
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      type: skiservice-logs
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: skiservice
  namespace: aspnet-api-containerized
spec:
  replicas: 1
  selector:
    matchLabels:
      app: skiservice
  template:
    metadata:
      labels:
        app: skiservice
    spec:
      containers:
        - name: skiservice
          image: fokklz/skiservice-api:latest
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ConnectionStrings__DefaultConnection
              valueFrom:
                secretKeyRef:
                  name: skiservice-secret
                  key: connection-string
            - name: CORS__AllowedOrigins
              value: 'http://127.0.0.1:3000,http://localhost:3000,http://127.0.0.1:5500,http://localhost:5500'
          volumeMounts:
            - name: skiservice-logs
              mountPath: /Logs
      volumes:
        - name: skiservice-logs
          persistentVolumeClaim:
            claimName: skiservice-logs-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: skiservice
  namespace: aspnet-api-containerized
spec:
  type: NodePort
  ports:
    - port: 8080
      # 30000 - 32767
      nodePort: 30003
  selector:
    app: skiservice
