apiVersion: v1
kind: Namespace
metadata:
  name: aspnet-api-containerized
---
apiVersion: v1
kind: Secret
metadata:
  name: mssql-secret
  namespace: aspnet-api-containerized
type: Opaque
data:
  sa-password: QVN0cm9uZ1whUGFzc3cwcmQ=
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mssql
  namespace: aspnet-api-containerized
spec:
  serviceName: 'mssql'
  replicas: 1
  selector:
    matchLabels:
      app: mssql
  template:
    metadata:
      labels:
        app: mssql
    spec:
      securityContext:
        fsGroup: 10001
      containers:
        - name: mssql
          image: mcr.microsoft.com/mssql/server:2019-latest
          ports:
            - containerPort: 1433
              name: tcpsql
          env:
            - name: ACCEPT_EULA
              value: 'Y'
            - name: MSSQL_ENABLE_HADR
              value: '1'
            - name: MSSQL_AGENT_ENABLED
              value: '1'
            - name: MSSQL_SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mssql-secret
                  key: sa-password
          volumeMounts:
            - name: mssql-data
              mountPath: '/var/opt/mssql'
  volumeClaimTemplates:
    - metadata:
        name: mssql-data
        namespace: aspnet-api-containerized
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 8Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mssql
  namespace: aspnet-api-containerized
spec:
  type: ClusterIP
  ports:
    - port: 1433
  selector:
    app: mssql
